/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

//Imports 
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kenez
 */
public class TelaMusicasDaPlaylist extends javax.swing.JFrame {

    /**
     * Creates new form TelaMusicasDaPlaylist
     */
    
    private int idPlaylist;
    
    public TelaMusicasDaPlaylist(int idPlaylist) {
        initComponents();
        this.idPlaylist = idPlaylist;
        carregarMusicas();
    }
    
    private void carregarMusicas(){
        try{
            //Conexao com bd
            Connection conn = dao.Conexao.conectar();
            
            //Comandos SQL
            String sql = "SELECT m.id, m.nome, a.nome AS artista, m.genero " + 
                         "FROM musica_playlist mp " + 
                         "JOIN musica m ON mp.id_musica = m.id " + 
                         "JOIN artista a ON m.id_artista = a.id " + 
                         "WHERE mp.id_playlist = ?";
            
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setInt(1 , idPlaylist);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tabelaMusicasPlaylist.getModel();
            model.setRowCount(0);
            
            while(rs.next()){
                //Atributos da tabela
                int id = rs.getInt("id");
                String nome = rs.getString("nome");
                String artista = rs.getString("artista");
                String genero = rs.getString("genero");
                
                model.addRow(new Object[]{id, nome, artista, genero});
            }
            
            conn.close();
        }catch(Exception e) {
            //possiveis erros
            JOptionPane.showMessageDialog(this,
                    "Erro ao carregar músicas!" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaMusicasPlaylist = new javax.swing.JTable();
        btnRemoverMusica = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Músicas dessa Playlist");

        tabelaMusicasPlaylist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Artista", "Gênero"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaMusicasPlaylist);

        btnRemoverMusica.setText("Remover Música");
        btnRemoverMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverMusicaActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemoverMusica)))
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoverMusica)
                    .addComponent(btnVoltar))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoverMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverMusicaActionPerformed
        // TODO add your handling code here:
        int linha = tabelaMusicasPlaylist.getSelectedRow();
        
        if (linha>=0){
            int idMusica = (int) tabelaMusicasPlaylist.getValueAt(linha, 0);
            
            try{
                //Conexao com banco
                Connection conn = dao.Conexao.conectar();
                        
                //Comandos SQL
                String sql = "DELETE FROM musica_playlist WHERE id_musica = ? AND id_playlist = ?";
                PreparedStatement stmt = conn.prepareStatement(sql);
                stmt.setInt(1 , idMusica);
                stmt.setInt(2 , idPlaylist);
                stmt.executeUpdate();
                conn.close();
                
                JOptionPane.showMessageDialog(this,
                        "Música removida da Playlist!");
                //Carrega depois da remoção
                carregarMusicas();
                
            }catch(Exception e){
                //Possiveis erros
                JOptionPane.showMessageDialog(this,
                        "Erro ao remover música!" + e.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(this,
                    "Selecione uma música para remover!");
        }
    }//GEN-LAST:event_btnRemoverMusicaActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        //Fecha essa tela
        this.dispose();
        //Abre essa outra
        new TelaPlaylist().setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemoverMusica;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaMusicasPlaylist;
    // End of variables declaration//GEN-END:variables
}
