/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

//Imports 
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kenez
 */
public class TelaHistorico extends javax.swing.JFrame {

    /**
     * Creates new form TelaHistorico
     */
    public TelaHistorico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntCurtidas = new javax.swing.JButton();
        btnDescurtidas = new javax.swing.JButton();
        btnUltimasBuscas = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaHistorico = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bntCurtidas.setText("Musicas Curtidas");
        bntCurtidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCurtidasActionPerformed(evt);
            }
        });

        btnDescurtidas.setText("Musicas Descurtidas");
        btnDescurtidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescurtidasActionPerformed(evt);
            }
        });

        btnUltimasBuscas.setText("Ultimas 10 Buscas");
        btnUltimasBuscas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimasBuscasActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        tabelaHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Artista", "Gênero"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaHistorico);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(bntCurtidas)
                        .addGap(31, 31, 31)
                        .addComponent(btnDescurtidas)
                        .addGap(45, 45, 45)
                        .addComponent(btnUltimasBuscas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntCurtidas)
                    .addComponent(btnDescurtidas)
                    .addComponent(btnUltimasBuscas))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntCurtidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCurtidasActionPerformed
        // TODO add your handling code here:
        //Aqui mostraremos na tabela as musicas curtidas pelo usuario
        int idUsuario = model.Sessao.getUsuario().getId();
        
        try{
            //Conexao com bd
            Connection conn = dao.Conexao.conectar();
            
            //Comandos SQL/ true para curtida
            String sql = "SELECT m.id, m.nome, a.nome AS artista, m.genero " + 
                         "FROM curtida c " + 
                         "JOIN musica m ON c.id_musica = m.id " + 
                         "JOIN artista a ON m.id_artista = a.id " + 
                         "WHERE c.id_usuario = ? AND c.status = true";
            
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setInt(1, idUsuario);
            ResultSet rs = stmt.executeQuery();
            
            DefaultTableModel model = (DefaultTableModel) 
                    tabelaHistorico.getModel();
            model.setRowCount(0); 
            
            //Mostrar de fato na tabela
            while (rs.next()){
                int id = rs.getInt("id");
                String nome = rs.getString( "nome");
                String artista = rs.getString( "artista");
                String genero = rs.getString("genero");
                
                model.addRow(new Object[]{ id, nome, artista, genero });
            }
            
            conn.close();
        }catch (Exception e) {
            //Possivel erro que pode dar
            JOptionPane.showMessageDialog(this, "Erro ao carregar curtidas!"
                    + e.getMessage());
        }
    }//GEN-LAST:event_bntCurtidasActionPerformed

    private void btnDescurtidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescurtidasActionPerformed
        // TODO add your handling code here:
        //Aqui mostraremos as musicas descurtidas pelo usuario
        int idUsuario = model.Sessao.getUsuario().getId();
        
        try{
            //Conexão com bd
            Connection conn = dao.Conexao.conectar();
            
            //Comandos para SQL/ false para descurtida
            String sql = "SELECT m.id, m.nome, a.nome AS artista, m.genero " + 
                         "FROM curtida c " + 
                         "JOIN musica m ON c.id_musica = m.id " + 
                         "JOIN artista a ON m.id_artista = a.id " + 
                         "WHERE c.id_usuario = ? AND c.status = false";
            
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setInt(1 , idUsuario);
            ResultSet rs = stmt.executeQuery();
            
            DefaultTableModel model = (DefaultTableModel)
                    tabelaHistorico.getModel();
            model.setRowCount(0);
            
            //Mostra de fato na tabela
            while(rs.next()){
                int id = rs.getInt("id");
                String nome = rs.getString("nome");
                String artista = rs.getString("artista");
                String genero = rs.getString("genero");
                
                model.addRow(new Object[]{ id, nome, artista, genero });
            }
            
            conn.close();
            
            
        }catch (Exception e){
            //Possiveis erros exibem isso:
            JOptionPane.showMessageDialog(this,
                    "Erro ao carregar descurtidas!" + e.getMessage());
        }
    }//GEN-LAST:event_btnDescurtidasActionPerformed

    private void btnUltimasBuscasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimasBuscasActionPerformed
        // TODO add your handling code here:
        //Aqui vamos exibir as 10 ultimas buscas
        int idUsuario = model.Sessao.getUsuario().getId();
        
        try{
            //conexao com bd
            Connection conn = dao.Conexao.conectar();
            
            //Comandos SQL/ limitado a 10 buscas
            String sql = "SELECT m.id, m.nome, a.nome AS artista, m.genero " + 
                         "FROM historico_busca h " + 
                         "JOIN musica m ON h.id_musica = m.id " + 
                         "JOIN artista a ON m.id_artista = a.id " + 
                         "WHERE h.id_usuario = ? " + 
                         "ORDER BY h.data DESC LIMIT 10";
            
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setInt(1 , idUsuario);
            ResultSet rs = stmt.executeQuery();
            
            DefaultTableModel model = (DefaultTableModel) 
                    tabelaHistorico.getModel();
            model.setRowCount(0);
            
            //Exibindo de verdade na tabela
            
            while(rs.next()) {
                int id = rs.getInt("id");
                String nome = rs.getString("nome");
                String artista = rs.getString("artista");
                String genero = rs.getString("genero");
                
                model.addRow(new Object[]{ id, nome, artista, genero });
            }
            conn.close();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao carregar as últimas buscas!" + e.getMessage());
        }
    }//GEN-LAST:event_btnUltimasBuscasActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        //Fecha essa tela
        this.dispose();
        //Abre essa outra(voltar)
        new TelaPrincipal().setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaHistorico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCurtidas;
    private javax.swing.JButton btnDescurtidas;
    private javax.swing.JButton btnUltimasBuscas;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaHistorico;
    // End of variables declaration//GEN-END:variables
}
